---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        language_version: python3.14
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.26
    hooks:
      - id: uv-lock
