# Generated by bin/drift/check_model_drift.py — do not edit by hand.
# Maps a still-served Mistral model id to its ISO-8601 retirement date.

DEPRECATED: dict[str, str] = {
    "mistral-moderation-latest": "2026-06-30T12:00:00Z",
}
