# Generated by bin/drift/check_model_drift.py — do not edit by hand.
# Maps a still-served Mistral model id to its ISO-8601 retirement date.

DEPRECATED: dict[str, str] = {
    "devstral-latest": "2026-08-31T12:00:00Z",
    "devstral-medium-latest": "2026-08-31T12:00:00Z",
    "mistral-code-agent-latest": "2026-08-31T12:00:00Z",
}
