# generated by datamodel-codegen:
#   filename:  tmp.UCqIsm0vUV.yml
#   timestamp: 2026-06-01T14:12:56+00:00

from typing import Any, Literal, NotRequired, TypedDict


class EmbeddingResponseData(TypedDict):
    object: NotRequired[str]
    embedding: NotRequired[list[float]]
    index: NotRequired[int]


class Prediction(TypedDict):
    """
    Enable users to specify an expected completion, optimizing response times by leveraging known or predictable content.
    """

    type: NotRequired[Literal["content"]]
    content: NotRequired[str]


class TranscriptionSegmentChunk(TypedDict):
    type: NotRequired[Literal["transcription_segment"]]
    text: str
    start: float
    end: float
    score: NotRequired[float | None]
    speaker_id: NotRequired[str | None]


class ValidationError(TypedDict):
    loc: list[str | int]
    msg: str
    type: str
    input: NotRequired[Any]
    ctx: NotRequired[dict[str, Any]]


class Function(TypedDict):
    name: str
    description: NotRequired[str]
    strict: NotRequired[bool]
    parameters: dict[str, Any]


class FunctionName(TypedDict):
    """
    this restriction of `Function` is used to select a specific function to call
    """

    name: str


class JsonSchema(TypedDict):
    name: str
    description: NotRequired[str | None]
    schema: dict[str, Any]
    strict: NotRequired[bool]


class PromptTokensDetails(TypedDict):
    """
    Token usage details for the prompt.
    """

    cached_tokens: NotRequired[int]


class AudioChunk(TypedDict):
    type: NotRequired[Literal["input_audio"]]
    input_audio: str | bytes


class DocumentURLChunk(TypedDict):
    type: NotRequired[Literal["document_url"]]
    document_url: str
    document_name: NotRequired[str | None]


class FileChunk(TypedDict):
    type: NotRequired[Literal["file"]]
    file_id: str


class FunctionCall(TypedDict):
    name: str
    arguments: dict[str, Any] | str


class ModerationLLMV1CategoryThresholds(TypedDict):
    sexual: NotRequired[float | None]
    hate_and_discrimination: NotRequired[float | None]
    violence_and_threats: NotRequired[float | None]
    dangerous_and_criminal_content: NotRequired[float | None]
    selfharm: NotRequired[float | None]
    health: NotRequired[float | None]
    financial: NotRequired[float | None]
    law: NotRequired[float | None]
    pii: NotRequired[float | None]


class ModerationLLMV2CategoryThresholds(TypedDict):
    sexual: NotRequired[float | None]
    hate_and_discrimination: NotRequired[float | None]
    violence_and_threats: NotRequired[float | None]
    dangerous: NotRequired[float | None]
    criminal: NotRequired[float | None]
    selfharm: NotRequired[float | None]
    health: NotRequired[float | None]
    financial: NotRequired[float | None]
    law: NotRequired[float | None]
    pii: NotRequired[float | None]
    jailbreaking: NotRequired[float | None]


class ReferenceChunk(TypedDict):
    type: NotRequired[Literal["reference"]]
    reference_ids: list[int]


class TextChunk(TypedDict):
    type: NotRequired[Literal["text"]]
    text: str


class AudioTranscriptionRequest(TypedDict):
    model: str
    file: NotRequired[bytes | None]
    file_url: NotRequired[str | None]
    file_id: NotRequired[str | None]
    language: NotRequired[str | None]
    temperature: NotRequired[float | None]
    stream: NotRequired[Literal[False]]
    diarize: NotRequired[bool]
    context_bias: NotRequired[list[str]]
    timestamp_granularities: NotRequired[list[Literal["segment", "word"]]]


class EmbeddingRequest(TypedDict):
    model: str
    metadata: NotRequired[dict[str, Any] | None]
    input: str | list[str]
    output_dimension: NotRequired[int | None]
    output_dtype: NotRequired[Literal["float", "int8", "uint8", "binary", "ubinary"]]
    encoding_format: NotRequired[Literal["float", "base64"]]


class HTTPValidationError(TypedDict):
    detail: NotRequired[list[ValidationError]]


class ResponseFormat(TypedDict):
    """
    Specify the format that the model must output. By default it will use `{ "type": "text" }`. Setting to `{ "type": "json_object" }` enables JSON mode, which guarantees the message the model generates is in JSON. When using JSON mode you MUST also instruct the model to produce JSON yourself with a system or a user message. Setting to `{ "type": "json_schema" }` enables JSON schema mode, which guarantees the message the model generates is in JSON and follows the schema you provide.
    """

    type: NotRequired[Literal["text", "json_object", "json_schema"]]
    json_schema: NotRequired[JsonSchema | None]


class Tool(TypedDict):
    type: NotRequired[Literal["function"]]
    function: Function


class ToolChoice(TypedDict):
    """
    ToolChoice is either a ToolChoiceEnum or a ToolChoice
    """

    type: NotRequired[Literal["function"]]
    function: FunctionName


class UsageInfo(TypedDict):
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    prompt_audio_seconds: NotRequired[int | None]
    num_cached_tokens: NotRequired[int | None]
    prompt_tokens_details: NotRequired[PromptTokensDetails | None]
    prompt_token_details: NotRequired[PromptTokensDetails | None]


class ModerationLLMV1Config(TypedDict):
    model_name: NotRequired[str]
    custom_category_thresholds: NotRequired[ModerationLLMV1CategoryThresholds | None]
    ignore_other_categories: NotRequired[bool]
    action: NotRequired[Literal["none", "block"]]


class ModerationLLMV2Config(TypedDict):
    model_name: NotRequired[str]
    custom_category_thresholds: NotRequired[ModerationLLMV2CategoryThresholds | None]
    ignore_other_categories: NotRequired[bool]
    action: NotRequired[Literal["none", "block"]]


class ToolCall(TypedDict):
    id: NotRequired[str]
    type: NotRequired[Literal["function"]]
    function: FunctionCall
    index: NotRequired[int]


class ImageURL(TypedDict):
    url: str
    detail: NotRequired[Literal["low", "auto", "high"] | None]


class ToolReferenceChunk(TypedDict):
    type: NotRequired[Literal["tool_reference"]]
    tool: (
        str
        | Literal[
            "web_search",
            "web_search_premium",
            "code_interpreter",
            "image_generation",
            "document_library",
        ]
    )
    title: str
    url: NotRequired[str | None]
    favicon: NotRequired[str | None]
    description: NotRequired[str | None]


class TranscriptionResponse(TypedDict):
    model: str
    text: str
    language: str | None
    segments: NotRequired[list[TranscriptionSegmentChunk]]
    usage: UsageInfo


class GuardrailConfig(TypedDict):
    block_on_error: NotRequired[bool]
    moderation_llm_v1: NotRequired[ModerationLLMV1Config | None]
    moderation_llm_v2: NotRequired[ModerationLLMV2Config | None]


class ResponseBase(TypedDict):
    id: NotRequired[str]
    object: NotRequired[str]
    model: NotRequired[str]
    usage: NotRequired[UsageInfo]


class ImageURLChunk(TypedDict):
    """
    {"type":"image_url","image_url":{"url":"data:image/png;base64,iVBORw0
    """

    type: NotRequired[Literal["image_url"]]
    image_url: ImageURL | str


class ThinkChunk(TypedDict):
    type: NotRequired[Literal["thinking"]]
    thinking: list[TextChunk | ToolReferenceChunk | ReferenceChunk]
    closed: NotRequired[bool]


class EmbeddingResponse(TypedDict):
    data: list[EmbeddingResponseData]
    id: str
    object: str
    model: str
    usage: UsageInfo


class ChatCompletionResponseBase(ResponseBase):
    created: NotRequired[int]


class DeltaMessage(TypedDict):
    role: NotRequired[str | None]
    content: NotRequired[
        str
        | list[
            TextChunk
            | ImageURLChunk
            | DocumentURLChunk
            | ReferenceChunk
            | FileChunk
            | ThinkChunk
            | AudioChunk
        ]
        | None
    ]
    tool_calls: NotRequired[list[ToolCall] | None]


class AssistantMessage(TypedDict):
    role: NotRequired[Literal["assistant"]]
    content: NotRequired[
        str
        | list[
            TextChunk
            | ImageURLChunk
            | DocumentURLChunk
            | ReferenceChunk
            | FileChunk
            | ThinkChunk
            | AudioChunk
        ]
        | None
    ]
    tool_calls: NotRequired[list[ToolCall] | None]
    prefix: NotRequired[bool]


class ChatCompletionChoice(TypedDict):
    index: int
    message: AssistantMessage
    finish_reason: Literal["stop", "length", "model_length", "error", "tool_calls"]


class SystemMessage(TypedDict):
    role: NotRequired[Literal["system"]]
    content: str | list[TextChunk | ThinkChunk]


class ToolMessage(TypedDict):
    role: NotRequired[Literal["tool"]]
    content: (
        str
        | list[
            TextChunk
            | ImageURLChunk
            | DocumentURLChunk
            | ReferenceChunk
            | FileChunk
            | ThinkChunk
            | AudioChunk
        ]
        | None
    )
    tool_call_id: NotRequired[str | None]
    name: NotRequired[str | None]


class UserMessage(TypedDict):
    role: NotRequired[Literal["user"]]
    content: (
        str
        | list[
            TextChunk
            | ImageURLChunk
            | DocumentURLChunk
            | ReferenceChunk
            | FileChunk
            | ThinkChunk
            | AudioChunk
        ]
        | None
    )


class CompletionResponseStreamChoice(TypedDict):
    index: int
    delta: DeltaMessage
    finish_reason: Literal["stop", "length", "error", "tool_calls"] | None


class ChatCompletionRequest(TypedDict):
    model: str
    temperature: NotRequired[float | None]
    top_p: NotRequired[float]
    max_tokens: NotRequired[int | None]
    stream: NotRequired[bool]
    stop: NotRequired[str | list[str]]
    random_seed: NotRequired[int | None]
    metadata: NotRequired[dict[str, Any] | None]
    messages: list[SystemMessage | UserMessage | AssistantMessage | ToolMessage]
    response_format: NotRequired[ResponseFormat]
    tools: NotRequired[list[Tool] | None]
    tool_choice: NotRequired[ToolChoice | Literal["auto", "none", "any", "required"]]
    presence_penalty: NotRequired[float]
    frequency_penalty: NotRequired[float]
    n: NotRequired[int | None]
    prediction: NotRequired[Prediction]
    parallel_tool_calls: NotRequired[bool]
    prompt_mode: NotRequired[Literal["reasoning"] | None]
    reasoning_effort: NotRequired[Literal["high", "none"]]
    guardrails: NotRequired[list[GuardrailConfig] | None]
    prompt_cache_key: NotRequired[str | None]
    safe_prompt: NotRequired[bool]


class ChatCompletionResponse(TypedDict):
    choices: list[ChatCompletionChoice]
    id: str
    object: str
    data: Any
    model: str
    usage: UsageInfo
    created: Any


class CompletionChunk(TypedDict):
    id: str
    object: NotRequired[str]
    created: NotRequired[int]
    model: str
    usage: NotRequired[UsageInfo]
    choices: list[CompletionResponseStreamChoice]


class CompletionEvent(TypedDict):
    data: CompletionChunk
